//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Phone1 { get; set; }
        public Nullable<byte> Phone1Type { get; set; }
        public string Phone2 { get; set; }
        public Nullable<byte> Phone2Type { get; set; }
        public string Phone3 { get; set; }
        public Nullable<byte> Phone3Type { get; set; }
        public string Email1 { get; set; }
        public Nullable<byte> Email1Type { get; set; }
        public string Email2 { get; set; }
        public Nullable<byte> Email2Type { get; set; }
        public string Email3 { get; set; }
        public Nullable<byte> Email3Type { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public int LastUpdatedBy { get; set; }
        public byte[] Ts { get; set; }
    }
}
