//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryDetail
    {
        public long HistoryDetailId { get; set; }
        public long HistoryHeaderId { get; set; }
        public string ColumnName { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
    
        public virtual HistoryHeader HistoryHeader { get; set; }
    }
}
