//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.RentPayments = new HashSet<RentPayment>();
            this.Rents = new HashSet<Rent>();
        }
    
        public int UnitId { get; set; }
        public string UnitName { get; set; }
        public int BuildingId { get; set; }
        public decimal SquareFootage { get; set; }
        public decimal NumberOfBedrooms { get; set; }
        public decimal NumberOfBathrooms { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public int LastUpdatedBy { get; set; }
        public byte[] Ts { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual ICollection<RentPayment> RentPayments { get; set; }
        public virtual ICollection<Rent> Rents { get; set; }
    }
}
